FROM ${DOCKER_PKGING_RPM_DIST_NAME}:${DOCKER_PKGING_RPM_DIST_VERSION}

MAINTAINER "Jiao Lin <jiao.lin@gmail.com>"

RUN yum install -y deltarpm
RUN yum install -y git cmake make gcc-c++ python python-devel rpm-build
RUN yum install -y curl
