FROM ${DOCKER_PKGING_DEB_DIST_NAME}:${DOCKER_PKGING_DEB_DIST_VERSION}

MAINTAINER "Jiao Lin <jiao.lin@gmail.com>"

RUN apt-get update
RUN apt-get install -y git build-essential
RUN apt-get install -y cmake
RUN apt-get install -y python python-dev
RUN apt-get install -y curl
