FROM ${DOCKER_ORG_NAME}/${PKG_NAME}-srpm-deps

MAINTAINER "Jiao Lin <jiao.lin@gmail.com>"

RUN yum install -y curl
RUN curl -s https://packagecloud.io/install/repositories/${PKGCLOUD_USERNAME}/${PKGCLOUD_REPO}/script.rpm.sh | bash
RUN yumdownloader --source ${PKG_NAME}-${VERSION}-${CPACK_PACKAGE_RELEASE}.src
RUN rpmbuild --rebuild ${PKG_NAME}-${VERSION}-${CPACK_PACKAGE_RELEASE}.src.rpm
RUN rpm -i ~/rpmbuild/RPMS/x86_64/${PKG_NAME}-${VERSION}-${CPACK_PACKAGE_RELEASE}.x86_64.rpm

RUN ${DOCKER_PKGING_TEST_SRPM}